var theme = ["Breaking Bad",
            "Milhouse Van Houten",
            "Saved by the Bell",
            "Seinfeld",
            "Frasier",
            "How I Met Your Mother",
            "Power Rangers",
            "Star Wars",
            "George Costanza",
            "Chandler Bing",
            "Joey Tribiani",
            "Kirk Van Houten",
            "Cosmo Kramer",
            "Sideshow Bob",
            "Game of Thrones",
            "90s Anime",
            "Pokemon",
            "Yugioh",
            "Digimon: Digital Monsters",
            "Sailor Moon" ,
            "Pulp Fiction",
            "Friends",
            "Russell Coight",
            "Cheez TV",
            "DJ Kahled",
            "Windows 95",
            "Street Fighter",
            "Street Sharks",
            "Ninja Turtles",
            "Lenny and Carl",
            "Keenan and Kel",
            "Malcom in the Middle",
            "Angry Beavers",
            "Hey Arnold",
            "Doug",
            "Ren and Stimpy",
            "Rugrats",
            "Beavis and Butthead",
            "Rocko's Modern Life",
            "Daria",
            "South Park",
            "Captain Planet",
            "Futurama",
            "Karl Stefanovic",
            "Con the Fruiterer",
            "Michael Beveridge",


          ]

var food = ["Chicken Nuggets",
            "Breakfast Cereal",
            "Bacon Topped Donuts",
            "NYC Style Pizza",
            "Late Night Doner Kebabs",
            "Fish Tacos",
            "Vegemite Sandwiches",
            "Fish Fingers",
            "Various BBQ'd Meats",
            "Bunning's Warehouse style Sausage Sandwiches",
            "Buckets of Pork Crackling covered in Caramel Sauce",
            "Deconstructed Lamingtons",
            "Servo Meat Pies",
            "Breakfast burritos",
            "Gyozas",
            "Artisinal Hot Dogs",
            "Gigantic Chicken Schnitzels",
            "Fajita share plates",
            "Bundaberg Rum Chocolate Milkshakes",
            "Spicy 'as fuck' Chicken wings",
            "Deep fried pickles",
            "only Victoria Bitter tinnies",
            "Melbourne Bitter longnecks",
            "Mi Goreng",
            "Masterfoods Tomato Sauce Sandwiches",
            "Halal Snack Packs with Chilli and Garlic Sauce in a fuckin styro."

            ]

var music = ["80's Punk Records",
            "nothing but WWE Superstar intro music",
            "The Sims 2: University soundtrack",
            "90s Hip Hop",
            "So Fresh Hits of Summer Complications",
            "Only the best Triple M bangaz",
            "Music from the Tony Hawks Pro Skater 2 Soundtrack",
            "Early 00'S Australian Punk. Like 28 Days",
            "The Australian Warped Tour '99 Tour Cd",
            "that one Eminem song every white person knows",
            "8-Bit Chiptunes",
            "Experimental Jazz",
            "Speed Metal",
            "Dubstep remixes of the latest memes",
            "That vapourwave album about Macintosh's",
            "Thrash Metal / Rap Crossover records",
            "Like a Bird by Nelly Furtado 24/7",
            "Shitty 00's Ska like Less than Jake",
            "music from all the artists that appeared on that Simpsons episode with the Smashing Pumpkins",
            "Easy Listening supermarket covers of the Red Hot Chilli Peppers",
            "the Australian classics like Midnight Oil and Cold Chisel",
            "Every Wheatus song, except Teenage Dirtbag",
            ]

var randomTheme = Math.floor(Math.random()*theme.length);
var randomFood = Math.floor(Math.random()*food.length);
var randomMusic = Math.floor(Math.random()*music.length);


// function writeAnswer() {
document.write("<h2>You should start a " + theme[randomTheme] + " themed bar that sells " + food[randomFood] + " and plays " + music[randomMusic] + ".</h2>");
// }
